// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409121842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f00ecee-932a-45a7-ba22-657722fe6cbc"),
                            Description = "Groceries, Meals",
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("ea6b4806-51e4-4e30-91e5-19c2d8e8b1f3"),
                            Description = "Drinks",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EndTime");

                    b.HasIndex("Status");

                    b.HasIndex("CategoryId", "Status");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d14170ce-2ef3-483a-a6e0-05d9c326ab93"),
                            CategoryId = new Guid("8f00ecee-932a-45a7-ba22-657722fe6cbc"),
                            Description = "Get half price on all freshly baked bread",
                            EndTime = new DateTime(2025, 4, 16, 16, 18, 42, 690, DateTimeKind.Local).AddTicks(4600),
                            Quantity = 20,
                            StartTime = new DateTime(2025, 4, 9, 16, 18, 42, 690, DateTimeKind.Local).AddTicks(4560),
                            Status = 0,
                            Title = "Bread",
                            UnitPrice = 2.50m
                        },
                        new
                        {
                            Id = new Guid("1a192769-0f4a-4e23-b1fc-69ce57f259d7"),
                            CategoryId = new Guid("ea6b4806-51e4-4e30-91e5-19c2d8e8b1f3"),
                            Description = "Purchase any coffee and get another one free",
                            EndTime = new DateTime(2025, 4, 23, 16, 18, 42, 690, DateTimeKind.Local).AddTicks(4610),
                            Quantity = 50,
                            StartTime = new DateTime(2025, 4, 9, 16, 18, 42, 690, DateTimeKind.Local).AddTicks(4610),
                            Status = 0,
                            Title = "Coffee",
                            UnitPrice = 3.99m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Offer", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Offers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
